name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: |
        dotnet publish --configuration Release
        mkdir result
        mv /home/runner/work/payday2-bundle-webdav/payday2-bundle-webdav/PD2-BundleDavServer/bin/Release/publish result/payday2-bundle-webdav
#    - name: Test
#      run: dotnet test --no-restore --verbosity normal
    - uses: actions/upload-artifact@v2
      with:
        name: payday2-bundle-webdav
        path: result/payday2-bundle-webdav